import type {
  AIStyledPostDraft,
  Blogger,
  DemoState,
  Offer,
  Post,
  Product,
  RequestPost,
  Seller,
  StyleAnalysis,
} from "@/lib/types";

const demoImages = {
  postUrbanBlack: "/generated/seedream-v1/post-urban-black.jpg",
  postBomberNight: "/generated/seedream-v1/post-bomber-night.jpg",
  postCleanCommute: "/generated/seedream-v1/post-clean-commute.jpg",
  postSandGallery: "/generated/seedream-v1/post-sand-gallery.jpg",
  postVintageLeather: "/generated/seedream-v1/post-vintage-leather.jpg",
  postDenimCafe: "/generated/seedream-v1/post-denim-cafe.jpg",
  postLooseSeoul: "/generated/seedream-v1/post-loose-seoul.jpg",
  postIvoryLayer: "/generated/seedream-v1/post-ivory-layer.jpg",
  postOliveTrench: "/generated/seedream-v1/post-olive-trench.jpg",
  productJacketBlack: "/generated/seedream-v1/product-jacket-black.jpg",
  productBlazerSand: "/generated/seedream-v1/product-blazer-sand.jpg",
  productDenimWash: "/generated/seedream-v1/product-denim-wash.jpg",
  productKnitIvory: "/generated/seedream-v1/product-knit-ivory.jpg",
  productTrenchOlive: "/generated/seedream-v1/product-trench-olive.jpg",
  productBomberNoir: "/generated/seedream-v1/product-bomber-noir.jpg",
};

function buildSizeGuide(sizes: string[]) {
  return sizes.map((size, index) => ({
    size,
    shoulder: `${42 + index * 2}cm`,
    chest: `${104 + index * 6}cm`,
    length: `${62 + index * 2}cm`,
  }));
}

export const seedSellers: Seller[] = [
  {
    id: "seller-urban",
    name: "Urban Seller",
    avatar: "US",
    bio: "擅长高街暗黑和利落外套，发帖快、出片稳。",
    revenue: 0,
    followerCount: 1280,
    styleFocus: "高街暗黑",
  },
  {
    id: "seller-minimal",
    name: "Daily Lab",
    avatar: "DL",
    bio: "通勤极简和 clean fit 常驻商户。",
    revenue: 0,
    followerCount: 940,
    styleFocus: "通勤极简",
  },
  {
    id: "seller-vintage",
    name: "Vintage Room",
    avatar: "VR",
    bio: "偏爱水洗牛仔、白T和周末市集复古感。",
    revenue: 0,
    followerCount: 1680,
    styleFocus: "美式复古",
  },
  {
    id: "seller-soft",
    name: "Loose Seoul",
    avatar: "LS",
    bio: "韩系宽松和柔和层次感单品集合。",
    revenue: 0,
    followerCount: 710,
    styleFocus: "韩系宽松",
  },
];

export const seedBloggers: Blogger[] = [
  {
    id: "blogger-me",
    name: "游客用户",
    avatar: "ME",
    bio: "用游客身份体验社区、找款、试穿和接商单。",
    followerCount: 128,
    styleTags: ["OOTD", "通勤", "Clean Fit", "本地会话"],
    coverImage: demoImages.postCleanCommute,
  },
  {
    id: "blogger-nora",
    name: "Nora 黑白日常",
    avatar: "NO",
    bio: "高街暗黑、通勤夹克和干净黑白比例。",
    followerCount: 14200,
    styleTags: ["高街暗黑", "通勤", "夹克"],
    coverImage: demoImages.postUrbanBlack,
  },
  {
    id: "blogger-mika",
    name: "Mika Clean Fit",
    avatar: "MI",
    bio: "低饱和通勤、看展穿搭和大地色外套。",
    followerCount: 18800,
    styleTags: ["Clean Fit", "通勤极简", "西装", "大地色"],
    coverImage: demoImages.postCleanCommute,
  },
  {
    id: "blogger-ryan",
    name: "Ryan Vintage",
    avatar: "RV",
    bio: "美式复古、水洗牛仔和咖啡店 OOTD。",
    followerCount: 9600,
    styleTags: ["美式复古", "牛仔", "层次穿搭"],
    coverImage: demoImages.postVintageLeather,
  },
  {
    id: "blogger-seo",
    name: "Seo 松弛感",
    avatar: "SO",
    bio: "韩系宽松、柔和针织和同色系叠穿。",
    followerCount: 12100,
    styleTags: ["韩系宽松", "针织", "柔和配色"],
    coverImage: demoImages.postLooseSeoul,
  },
];

export const seedProducts: Product[] = [
  {
    id: "product-jacket-black",
    sellerId: "seller-urban",
    name: "Urban 黑色短款棒球夹克",
    price: 189,
    stock: 3,
    sizes: ["S", "M", "L"],
    sizeGuide: buildSizeGuide(["S", "M", "L"]),
    material: "棉感尼龙混纺，短款 rib 领口与下摆",
    care: "建议冷水轻柔洗涤，悬挂晾干，低温熨烫。",
    tags: ["高街暗黑", "短款夹克", "棒球领"],
    image: demoImages.productJacketBlack,
    detailImages: [demoImages.productJacketBlack, demoImages.postUrbanBlack],
    similarityScore: 92,
    similarityReason: "和穿搭图里的黑色短外套一致，短款比例、rib 领口和干净拉链适合高街通勤。",
    tryOnPreset: demoImages.postUrbanBlack,
    sourcePostId: "post-urban-black",
    sourcePostIds: ["post-urban-black"],
  },
  {
    id: "product-blazer-sand",
    sellerId: "seller-minimal",
    name: "Daily 沙色宽松西装外套",
    price: 249,
    stock: 5,
    sizes: ["M", "L"],
    sizeGuide: buildSizeGuide(["M", "L"]),
    material: "柔软 TR 西装面料，低饱和沙色",
    care: "建议干洗或低温蒸汽护理，避免长时间暴晒。",
    tags: ["通勤极简", "沙色西装", "Clean Fit"],
    image: demoImages.productBlazerSand,
    detailImages: [demoImages.productBlazerSand, demoImages.postCleanCommute],
    similarityScore: 90,
    similarityReason: "封面里同款沙色西装外套，低饱和颜色和宽松肩线让通勤穿搭更柔和。",
    tryOnPreset: demoImages.postCleanCommute,
    sourcePostId: "post-clean-commute",
    sourcePostIds: ["post-clean-commute", "post-sand-gallery"],
  },
  {
    id: "product-denim-wash",
    sellerId: "seller-vintage",
    name: "Vintage 浅水洗牛仔夹克",
    price: 168,
    stock: 6,
    sizes: ["S", "M", "L"],
    sizeGuide: buildSizeGuide(["S", "M", "L"]),
    material: "中磅水洗棉牛仔，浅蓝做旧纹理",
    care: "深浅色分开洗，反面晾晒以保留水洗层次。",
    tags: ["美式复古", "水洗牛仔", "咖啡店穿搭"],
    image: demoImages.productDenimWash,
    detailImages: [demoImages.productDenimWash, demoImages.postVintageLeather],
    similarityScore: 86,
    similarityReason: "和博主图里的浅蓝牛仔外套一致，胸袋、金属扣和水洗纹理都很适合复古日常。",
    tryOnPreset: demoImages.postVintageLeather,
    sourcePostId: "post-vintage-leather",
    sourcePostIds: ["post-vintage-leather", "post-denim-cafe"],
  },
  {
    id: "product-knit-ivory",
    sellerId: "seller-soft",
    name: "Loose Seoul 象牙白宽松针织",
    price: 139,
    stock: 8,
    sizes: ["M", "L", "XL"],
    sizeGuide: buildSizeGuide(["M", "L", "XL"]),
    material: "柔软针织混纺，象牙白细纹理",
    care: "建议手洗平铺晾干，避免衣架悬挂导致变形。",
    tags: ["韩系宽松", "象牙针织", "松弛感"],
    image: demoImages.productKnitIvory,
    detailImages: [demoImages.productKnitIvory, demoImages.postLooseSeoul],
    similarityScore: 88,
    similarityReason: "封面中的象牙白针织上身柔和，宽松落肩和浅色系很适合韩系松弛感。",
    tryOnPreset: demoImages.postLooseSeoul,
    sourcePostId: "post-loose-seoul",
    sourcePostIds: ["post-loose-seoul", "post-ivory-layer"],
  },
  {
    id: "product-trench-olive",
    sellerId: "seller-minimal",
    name: "Daily 橄榄绿系带风衣",
    price: 279,
    stock: 4,
    sizes: ["S", "M", "L"],
    sizeGuide: buildSizeGuide(["S", "M", "L"]),
    material: "轻量棉感风衣布，低饱和橄榄绿",
    care: "局部污渍湿布擦拭，低温熨烫恢复廓形。",
    tags: ["通勤极简", "橄榄风衣", "系带外套"],
    image: demoImages.productTrenchOlive,
    detailImages: [demoImages.productTrenchOlive, demoImages.postOliveTrench],
    similarityScore: 84,
    similarityReason: "和穿搭图里的橄榄绿风衣对应，翻领、腰带和中长款轮廓清楚，适合轻熟通勤。",
    tryOnPreset: demoImages.postOliveTrench,
    sourcePostIds: ["post-olive-trench", "post-clean-commute"],
  },
  {
    id: "product-bomber-noir",
    sellerId: "seller-urban",
    name: "Urban 黑色尼龙飞行夹克",
    price: 219,
    stock: 4,
    sizes: ["M", "L", "XL"],
    sizeGuide: buildSizeGuide(["M", "L", "XL"]),
    material: "微光泽尼龙面料，袖袋与 rib 下摆",
    care: "建议轻柔机洗，避免高温烘干。",
    tags: ["高街暗黑", "飞行夹克", "尼龙外套"],
    image: demoImages.productBomberNoir,
    detailImages: [demoImages.productBomberNoir, demoImages.postBomberNight],
    similarityScore: 89,
    similarityReason: "封面里同款黑色飞行夹克，袖袋和短款 rib 下摆让灰西裤穿搭更有高街感。",
    tryOnPreset: demoImages.postBomberNight,
    sourcePostIds: ["post-bomber-night", "post-urban-black"],
  },
];

const requestOffersOne: Offer[] = [
  {
    sellerId: "seller-urban",
    productId: "product-jacket-black",
    price: 189,
    similarityScore: 92,
    note: "短款比例和黑色 rib 领最接近，适合直接复刻图里的通勤高街感。",
  },
  {
    sellerId: "seller-urban",
    productId: "product-bomber-noir",
    price: 219,
    similarityScore: 88,
    note: "如果想要袖袋和更强街头感，黑色飞行夹克会更接近进阶版。",
  },
  {
    sellerId: "seller-minimal",
    productId: "product-blazer-sand",
    price: 249,
    similarityScore: 72,
    note: "颜色不一样，但同样适合干净通勤场景，可以作为低饱和替代。",
  },
];

const requestOffersTwo: Offer[] = [
  {
    sellerId: "seller-soft",
    productId: "product-knit-ivory",
    price: 139,
    similarityScore: 88,
    note: "象牙白针织和韩系松弛感最接近，预算内可以直接试。",
  },
  {
    sellerId: "seller-minimal",
    productId: "product-trench-olive",
    price: 279,
    similarityScore: 76,
    note: "如果想从软糯针织换成更轻熟的外套，可以选橄榄绿风衣。",
  },
];

export const seedRequests: RequestPost[] = [
  {
    id: "request-city-black",
    image: demoImages.postUrbanBlack,
    description: "想找图里这种黑色短款外套，白T加高腰裤就能穿出比例，预算 220 内。",
    budget: 200,
    tags: ["高街暗黑", "短款夹克", "通勤"],
    expectedItem: "黑色短款外套",
    matchedOffers: requestOffersOne,
    createdAt: "2026-05-01T09:45:00.000Z",
  },
  {
    id: "request-soft-knit",
    image: demoImages.postLooseSeoul,
    description: "想找这种温柔韩系浅色上衣，最好是象牙白、宽松一点，能搭浅色裤子。",
    budget: 180,
    tags: ["韩系宽松", "象牙针织", "松弛感"],
    expectedItem: "象牙白宽松针织",
    matchedOffers: requestOffersTwo,
    createdAt: "2026-05-01T08:10:00.000Z",
  },
];

export const seedPosts: Post[] = [
  {
    id: "post-urban-black",
    type: "seller-look",
    sellerId: "seller-urban",
    bloggerId: "blogger-nora",
    productId: "product-jacket-black",
    productIds: ["product-jacket-black"],
    productTags: [
      { productId: "product-jacket-black", label: "黑色短夹克", x: 55, y: 42 },
    ],
    title: "黑色短夹克 + 高腰阔腿裤，比例直接拉满",
    body: "这套就是我最近最稳的高街通勤公式：短款黑夹克压住上半身，白T做留白，下装选高腰黑裤，干净但有态度。",
    coverImage: demoImages.postUrbanBlack,
    styleTags: ["高街暗黑", "短款夹克", "黑白灰"],
    likes: 324,
    createdAt: "2026-05-01T10:10:00.000Z",
    priceLabel: "¥189 起",
  },
  {
    id: "post-clean-commute",
    type: "seller-look",
    sellerId: "seller-minimal",
    bloggerId: "blogger-mika",
    productId: "product-blazer-sand",
    productIds: ["product-blazer-sand"],
    productTags: [
      { productId: "product-blazer-sand", label: "沙色西装", x: 50, y: 38 },
    ],
    title: "沙色西装真的很适合春夏通勤",
    body: "比黑西装轻很多，但还是有精神。里面只搭白色基础款，下装顺色，整个人会显得干净、松弛、没有用力过猛。",
    coverImage: demoImages.postCleanCommute,
    styleTags: ["通勤极简", "沙色西装", "Clean Fit"],
    likes: 211,
    createdAt: "2026-05-01T09:20:00.000Z",
    priceLabel: "¥249 起",
  },
  {
    id: "post-vintage-leather",
    type: "seller-look",
    sellerId: "seller-vintage",
    bloggerId: "blogger-ryan",
    productId: "product-denim-wash",
    productIds: ["product-denim-wash"],
    productTags: [
      { productId: "product-denim-wash", label: "浅水洗牛仔", x: 48, y: 42 },
    ],
    title: "白T + 水洗牛仔夹克，咖啡店门口很出片",
    body: "这件浅水洗牛仔不用复杂搭配，白T、深色直筒裤和棕色皮带就够了。阳光一打，复古感会很自然。",
    coverImage: demoImages.postVintageLeather,
    styleTags: ["美式复古", "水洗牛仔", "咖啡店穿搭"],
    likes: 175,
    createdAt: "2026-05-01T07:55:00.000Z",
    priceLabel: "¥168 起",
  },
  {
    id: "post-loose-seoul",
    type: "seller-look",
    sellerId: "seller-soft",
    bloggerId: "blogger-seo",
    productId: "product-knit-ivory",
    productIds: ["product-knit-ivory"],
    productTags: [
      { productId: "product-knit-ivory", label: "象牙白针织", x: 48, y: 40 },
    ],
    title: "象牙白针织，韩系松弛感不用太复杂",
    body: "浅色针织的关键是别太紧，落肩和宽松下摆会更自然。搭浅灰或米色下装，整套就很温柔。",
    coverImage: demoImages.postLooseSeoul,
    styleTags: ["韩系宽松", "象牙针织", "松弛感"],
    likes: 148,
    createdAt: "2026-05-01T06:40:00.000Z",
    priceLabel: "¥139 起",
  },
  {
    id: "post-bomber-night",
    type: "seller-look",
    sellerId: "seller-urban",
    bloggerId: "blogger-nora",
    productId: "product-bomber-noir",
    productIds: ["product-bomber-noir"],
    productTags: [
      { productId: "product-bomber-noir", label: "黑色飞行夹克", x: 55, y: 42 },
    ],
    title: "黑色飞行夹克配灰西裤，暗黑但不沉闷",
    body: "同样是黑外套，这套把下装换成灰色西裤，街头感会被中和一点。适合想穿高街但又不想太重的人。",
    coverImage: demoImages.postBomberNight,
    styleTags: ["高街暗黑", "飞行夹克", "灰西裤"],
    likes: 267,
    createdAt: "2026-05-01T05:50:00.000Z",
    priceLabel: "¥219 起",
  },
  {
    id: "post-olive-trench",
    type: "seller-look",
    sellerId: "seller-minimal",
    bloggerId: "blogger-mika",
    productId: "product-trench-olive",
    productIds: ["product-trench-olive"],
    productTags: [
      { productId: "product-trench-olive", label: "橄榄绿风衣", x: 50, y: 42 },
    ],
    title: "橄榄绿风衣比黑白灰更有记忆点",
    body: "这件风衣的颜色很适合通勤，不会太抢但比基础色更有层次。白色内搭和浅色裤子能把整体提亮。",
    coverImage: demoImages.postOliveTrench,
    styleTags: ["通勤极简", "橄榄风衣", "轻熟"],
    likes: 193,
    createdAt: "2026-05-01T05:05:00.000Z",
    priceLabel: "¥279 起",
  },
  {
    id: "post-denim-cafe",
    type: "seller-look",
    sellerId: "seller-vintage",
    bloggerId: "blogger-ryan",
    productId: "product-denim-wash",
    productIds: ["product-denim-wash"],
    productTags: [
      { productId: "product-denim-wash", label: "水洗牛仔夹克", x: 49, y: 42 },
    ],
    title: "市集周末就穿这件水洗牛仔",
    body: "木质摊位和浅蓝牛仔真的很搭。里面保持白T，裤子选深色，整套会更像随手拍到的周末OOTD。",
    coverImage: demoImages.postDenimCafe,
    styleTags: ["美式复古", "水洗牛仔", "周末市集"],
    likes: 142,
    createdAt: "2026-05-01T04:35:00.000Z",
    priceLabel: "¥168 起",
  },
  {
    id: "post-ivory-layer",
    type: "seller-look",
    sellerId: "seller-soft",
    bloggerId: "blogger-seo",
    productId: "product-knit-ivory",
    productIds: ["product-knit-ivory"],
    productTags: [
      { productId: "product-knit-ivory", label: "象牙白针织", x: 52, y: 40 },
    ],
    title: "浅色系穿搭想温柔，就别选太冷的白",
    body: "象牙白会比纯白更软，和浅灰、米色放在一起没有割裂感。日常拍照也更显气色。",
    coverImage: demoImages.postIvoryLayer,
    styleTags: ["韩系宽松", "象牙针织", "同色系"],
    likes: 229,
    createdAt: "2026-05-01T03:30:00.000Z",
    priceLabel: "¥139 起",
  },
  {
    id: "post-sand-gallery",
    type: "seller-look",
    sellerId: "seller-minimal",
    bloggerId: "blogger-mika",
    productId: "product-blazer-sand",
    productIds: ["product-blazer-sand"],
    productTags: [
      { productId: "product-blazer-sand", label: "沙色西装", x: 54, y: 38 },
    ],
    title: "看展穿沙色西装，干净但不会太正式",
    body: "这一套比办公室西装更放松，沙色外套配浅色内搭，适合美术馆、咖啡店和轻通勤。",
    coverImage: demoImages.postSandGallery,
    styleTags: ["Clean Fit", "沙色西装", "看展穿搭"],
    likes: 318,
    createdAt: "2026-05-01T02:45:00.000Z",
    priceLabel: "¥249 起",
  },
  ...seedRequests.map<Post>((request) => ({
    id: `post-${request.id}`,
    type: "buyer-request",
    requestId: request.id,
    title: `征集：${request.expectedItem}`,
    body: request.description,
    coverImage: request.image,
    styleTags: request.tags,
    likes: Math.floor(request.matchedOffers.length * 18 + 36),
    createdAt: request.createdAt,
    priceLabel: `预算 ¥${request.budget}`,
  })),
];

export const seedDemoState: DemoState = {
  sellers: seedSellers,
  bloggers: seedBloggers,
  products: seedProducts,
  posts: seedPosts,
  requests: seedRequests,
  collabRequests: [],
  viewer: {
    balance: 500,
    likedPostIds: [],
    savedPostIds: [],
    followedSellerIds: [],
    followedBloggerIds: [],
    favoriteProductIds: [],
    cartProductIds: [],
    sectionVisibility: {
      likedPosts: "public",
      savedPosts: "public",
      followedBloggers: "public",
      followedSellers: "public",
    },
    orders: [],
    viewHistory: [],
  },
};

export function buildDraftFromProduct(
  product: Product,
  seller: Seller,
): AIStyledPostDraft {
  const primaryTag = product.tags[0] ?? "风格穿搭";

  return {
    productId: product.id,
    sellerId: seller.id,
    title: `${primaryTag}今天这样穿，最容易出片`,
    caption: `把 ${product.name} 做成一套可直接复制的 ${primaryTag} 模板。上身重点是 ${product.tags
      .slice(1)
      .join(" / ")}，适合喜欢 ${seller.styleFocus} 的用户直接进商品看同款。`,
    modelImage: product.tryOnPreset,
    tags: product.tags,
    status: "ready",
  };
}

export function buildStyleAnalysis(input: string): StyleAnalysis {
  return {
    sourceType: "xhs-link",
    sourceInput: input,
    coverImage: demoImages.postCleanCommute,
    styleTags: ["Clean Fit", "通勤极简", "大地色", "宽松西装"],
    summary:
      "整体是低饱和 clean fit 通勤风，核心在宽松西装、干净内搭和利落层次。适合买大地色外套或挺阔针织，再做一次试穿确认版型。",
    matchedProducts: [
      "product-blazer-sand",
      "product-trench-olive",
      "product-knit-ivory",
    ],
  };
}
