import type {
  AIStyledPostDraft,
  Blogger,
  DemoState,
  Offer,
  Post,
  Product,
  RequestPost,
  Seller,
  StyleAnalysis,
} from "@/lib/types";

const demoImages = {
  post1:
    "https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=1200&q=80",
  post2:
    "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1200&q=80",
  post3:
    "https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=1200&q=80",
  post4:
    "https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=1200&q=80",
  product1:
    "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=900&q=80",
  product2:
    "https://images.unsplash.com/photo-1503341455253-b2e723bb3dbb?auto=format&fit=crop&w=900&q=80",
  product3:
    "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=900&q=80",
  product4:
    "https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=900&q=80",
  product5:
    "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=80",
  product6:
    "https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=900&q=80",
  tryOn1:
    "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=1200&q=80",
  tryOn2:
    "https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=1200&q=80",
  tryOn3:
    "https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=1200&q=80",
  tryOn4:
    "https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?auto=format&fit=crop&w=1200&q=80",
  request1:
    "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=1200&q=80",
  request2:
    "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=1200&q=80",
};

function buildSizeGuide(sizes: string[]) {
  return sizes.map((size, index) => ({
    size,
    shoulder: `${42 + index * 2}cm`,
    chest: `${104 + index * 6}cm`,
    length: `${62 + index * 2}cm`,
  }));
}

export const seedSellers: Seller[] = [
  {
    id: "seller-urban",
    name: "Urban Seller",
    avatar: "US",
    bio: "擅长高街暗黑和利落外套，发帖快、出片稳。",
    revenue: 0,
    followerCount: 1280,
    styleFocus: "高街暗黑",
  },
  {
    id: "seller-minimal",
    name: "Daily Lab",
    avatar: "DL",
    bio: "通勤极简和 clean fit 常驻商户。",
    revenue: 0,
    followerCount: 940,
    styleFocus: "通勤极简",
  },
  {
    id: "seller-vintage",
    name: "Vintage Room",
    avatar: "VR",
    bio: "偏爱复古牛仔、皮衣和做旧工装。",
    revenue: 0,
    followerCount: 1680,
    styleFocus: "美式复古",
  },
  {
    id: "seller-soft",
    name: "Loose Seoul",
    avatar: "LS",
    bio: "韩系宽松和柔和层次感单品集合。",
    revenue: 0,
    followerCount: 710,
    styleFocus: "韩系宽松",
  },
];

export const seedBloggers: Blogger[] = [
  {
    id: "blogger-me",
    name: "游客用户",
    avatar: "ME",
    bio: "用游客身份体验社区、找款、试穿和接商单。",
    followerCount: 128,
    styleTags: ["OOTD", "通勤", "Clean Fit", "本地会话"],
    coverImage: demoImages.post4,
  },
  {
    id: "blogger-nora",
    name: "Nora 黑白日常",
    avatar: "NO",
    bio: "高街暗黑、通勤夹克和干净黑白比例。",
    followerCount: 14200,
    styleTags: ["高街暗黑", "通勤", "夹克"],
    coverImage: demoImages.post1,
  },
  {
    id: "blogger-mika",
    name: "Mika Clean Fit",
    avatar: "MI",
    bio: "低饱和通勤、看展穿搭和大地色外套。",
    followerCount: 18800,
    styleTags: ["Clean Fit", "通勤极简", "西装", "大地色"],
    coverImage: demoImages.post4,
  },
  {
    id: "blogger-ryan",
    name: "Ryan Vintage",
    avatar: "RV",
    bio: "美式复古、水洗牛仔和咖啡店 OOTD。",
    followerCount: 9600,
    styleTags: ["美式复古", "牛仔", "层次穿搭"],
    coverImage: demoImages.post2,
  },
  {
    id: "blogger-seo",
    name: "Seo 松弛感",
    avatar: "SO",
    bio: "韩系宽松、柔和针织和同色系叠穿。",
    followerCount: 12100,
    styleTags: ["韩系宽松", "针织", "柔和配色"],
    coverImage: demoImages.post3,
  },
];

export const seedProducts: Product[] = [
  {
    id: "product-jacket-black",
    sellerId: "seller-urban",
    name: "Urban 黑色短夹克",
    price: 189,
    stock: 3,
    sizes: ["S", "M", "L"],
    sizeGuide: buildSizeGuide(["S", "M", "L"]),
    material: "棉混纺斜纹布，挺阔微哑光表面",
    care: "建议冷水轻柔洗涤，悬挂晾干，低温熨烫。",
    tags: ["高街暗黑", "短夹克", "显肩线"],
    image: demoImages.product1,
    detailImages: [demoImages.product1, demoImages.post1],
    similarityScore: 92,
    similarityReason: "与原图在黑色基调、利落肩线和通勤暗黑感上高度接近。",
    tryOnPreset: demoImages.tryOn1,
    sourcePostId: "post-urban-black",
    sourcePostIds: ["post-urban-black", "post-black-commute"],
  },
  {
    id: "product-blazer-sand",
    sellerId: "seller-minimal",
    name: "Daily 沙色宽松西装",
    price: 249,
    stock: 5,
    sizes: ["M", "L"],
    sizeGuide: buildSizeGuide(["M", "L"]),
    material: "TR 西装面料，含少量弹力纤维",
    care: "建议干洗或低温蒸汽护理，避免长时间暴晒。",
    tags: ["通勤极简", "西装", "大地色"],
    image: demoImages.product4,
    detailImages: [demoImages.product4, demoImages.post4],
    similarityScore: 90,
    similarityReason: "颜色克制、廓形宽松，适合 clean fit 与通勤极简场景。",
    tryOnPreset: demoImages.tryOn3,
    sourcePostId: "post-clean-commute",
    sourcePostIds: ["post-clean-commute", "post-sand-gallery"],
  },
  {
    id: "product-denim-wash",
    sellerId: "seller-vintage",
    name: "Vintage 做旧牛仔外套",
    price: 168,
    stock: 6,
    sizes: ["S", "M", "L"],
    sizeGuide: buildSizeGuide(["S", "M", "L"]),
    material: "水洗棉牛仔，做旧纹理",
    care: "深浅色分开洗，反面晾晒以保留水洗层次。",
    tags: ["美式复古", "牛仔", "做旧"],
    image: demoImages.product2,
    detailImages: [demoImages.product2, demoImages.post2],
    similarityScore: 86,
    similarityReason: "复古水洗和层次穿法与灵感图相近，价格也更友好。",
    tryOnPreset: demoImages.tryOn2,
    sourcePostId: "post-vintage-leather",
    sourcePostIds: ["post-vintage-leather", "post-denim-cafe"],
  },
  {
    id: "product-knit-ivory",
    sellerId: "seller-soft",
    name: "Loose Seoul 象牙色针织",
    price: 139,
    stock: 8,
    sizes: ["M", "L", "XL"],
    sizeGuide: buildSizeGuide(["M", "L", "XL"]),
    material: "腈纶羊毛混纺，柔软亲肤",
    care: "建议手洗平铺晾干，避免衣架悬挂导致变形。",
    tags: ["韩系宽松", "针织", "柔和叠穿"],
    image: demoImages.product5,
    detailImages: [demoImages.product5, demoImages.post3],
    similarityScore: 88,
    similarityReason: "柔和配色和松弛感与韩系宽松风格高度匹配。",
    tryOnPreset: demoImages.tryOn4,
    sourcePostId: "post-loose-seoul",
    sourcePostIds: ["post-loose-seoul", "post-ivory-layer"],
  },
  {
    id: "product-trench-olive",
    sellerId: "seller-minimal",
    name: "Daily 橄榄风衣",
    price: 279,
    stock: 4,
    sizes: ["S", "M", "L"],
    sizeGuide: buildSizeGuide(["S", "M", "L"]),
    material: "防泼水棉感风衣布，轻量有垂坠",
    care: "局部污渍湿布擦拭，低温熨烫恢复廓形。",
    tags: ["通勤极简", "风衣", "橄榄色"],
    image: demoImages.product6,
    detailImages: [demoImages.product6, demoImages.post4],
    similarityScore: 84,
    similarityReason: "适合需要轻正式气质的找款，轮廓与色温接近。",
    tryOnPreset: demoImages.tryOn3,
    sourcePostIds: ["post-olive-trench", "post-clean-commute"],
  },
  {
    id: "product-bomber-noir",
    sellerId: "seller-urban",
    name: "Urban 暗黑飞行夹克",
    price: 219,
    stock: 4,
    sizes: ["M", "L", "XL"],
    sizeGuide: buildSizeGuide(["M", "L", "XL"]),
    material: "尼龙混纺飞行面料，内里薄夹棉",
    care: "建议轻柔机洗，避免高温烘干。",
    tags: ["高街暗黑", "飞行夹克", "层次感"],
    image: demoImages.product3,
    detailImages: [demoImages.product3, demoImages.post1],
    similarityScore: 89,
    similarityReason: "保留硬挺轮廓，同时在街头感上更强烈。",
    tryOnPreset: demoImages.tryOn1,
    sourcePostIds: ["post-bomber-night", "post-urban-black"],
  },
];

const requestOffersOne: Offer[] = [
  {
    sellerId: "seller-urban",
    productId: "product-jacket-black",
    price: 189,
    similarityScore: 92,
    note: "黑色廓形最接近，直接适合高街暗黑路线。",
  },
  {
    sellerId: "seller-vintage",
    productId: "product-denim-wash",
    price: 168,
    similarityScore: 86,
    note: "如果更想要复古一点的街头感，可以选这件。",
  },
  {
    sellerId: "seller-minimal",
    productId: "product-blazer-sand",
    price: 249,
    similarityScore: 79,
    note: "风格会更干净，更偏通勤。",
  },
];

const requestOffersTwo: Offer[] = [
  {
    sellerId: "seller-soft",
    productId: "product-knit-ivory",
    price: 139,
    similarityScore: 88,
    note: "最接近韩系松弛感，预算内。",
  },
  {
    sellerId: "seller-minimal",
    productId: "product-trench-olive",
    price: 279,
    similarityScore: 83,
    note: "如果接受更成熟一点的版本，可以选风衣。",
  },
];

export const seedRequests: RequestPost[] = [
  {
    id: "request-city-black",
    image: demoImages.request1,
    description: "想找一件图里这种黑色短夹克，预算 200 内，最好通勤也能穿。",
    budget: 200,
    tags: ["高街暗黑", "通勤", "黑色夹克"],
    expectedItem: "黑色短夹克",
    matchedOffers: requestOffersOne,
    createdAt: "2026-05-01T09:45:00.000Z",
  },
  {
    id: "request-soft-knit",
    image: demoImages.request2,
    description: "想复刻这种宽松韩系氛围，优先针织或轻外套。",
    budget: 180,
    tags: ["韩系宽松", "松弛感", "针织"],
    expectedItem: "宽松针织",
    matchedOffers: requestOffersTwo,
    createdAt: "2026-05-01T08:10:00.000Z",
  },
];

export const seedPosts: Post[] = [
  {
    id: "post-urban-black",
    type: "seller-look",
    sellerId: "seller-urban",
    bloggerId: "blogger-nora",
    productId: "product-jacket-black",
    productIds: ["product-jacket-black", "product-bomber-noir"],
    productTags: [
      { productId: "product-jacket-black", label: "短夹克", x: 58, y: 36 },
      { productId: "product-bomber-noir", label: "飞行夹克", x: 42, y: 58 },
    ],
    title: "今天这套高街暗黑通勤真的太稳了",
    body: "我把黑色短夹克做成了通勤能穿、夜里也有态度的一套。肩线利落，内搭留白，日常很好复制。",
    coverImage: demoImages.post1,
    styleTags: ["高街暗黑", "通勤", "夹克"],
    likes: 324,
    createdAt: "2026-05-01T10:10:00.000Z",
    priceLabel: "¥189 起",
  },
  {
    id: "post-clean-commute",
    type: "seller-look",
    sellerId: "seller-minimal",
    bloggerId: "blogger-mika",
    productId: "product-blazer-sand",
    productIds: ["product-blazer-sand", "product-trench-olive"],
    productTags: [
      { productId: "product-blazer-sand", label: "宽松西装", x: 55, y: 34 },
      { productId: "product-trench-olive", label: "橄榄风衣", x: 36, y: 61 },
    ],
    title: "一套就能出门的 clean fit 通勤模板",
    body: "低饱和的大地色和放松的西装版型，会让整套更贵一点但不压人，适合上班、约会、看展。",
    coverImage: demoImages.post4,
    styleTags: ["通勤极简", "Clean Fit", "西装"],
    likes: 211,
    createdAt: "2026-05-01T09:20:00.000Z",
    priceLabel: "¥249 起",
  },
  {
    id: "post-vintage-leather",
    type: "seller-look",
    sellerId: "seller-vintage",
    bloggerId: "blogger-ryan",
    productId: "product-denim-wash",
    productIds: ["product-denim-wash", "product-jacket-black"],
    productTags: [
      { productId: "product-denim-wash", label: "做旧牛仔", x: 50, y: 39 },
      { productId: "product-jacket-black", label: "黑色夹克", x: 64, y: 63 },
    ],
    title: "想要美式复古氛围感，先从水洗牛仔开始",
    body: "这套把复古牛仔和深色内搭做了平衡，不会太夸张，但一眼能看出层次和态度。",
    coverImage: demoImages.post2,
    styleTags: ["美式复古", "牛仔", "层次穿搭"],
    likes: 175,
    createdAt: "2026-05-01T07:55:00.000Z",
    priceLabel: "¥168 起",
  },
  {
    id: "post-loose-seoul",
    type: "seller-look",
    sellerId: "seller-soft",
    bloggerId: "blogger-seo",
    productId: "product-knit-ivory",
    productIds: ["product-knit-ivory", "product-blazer-sand"],
    productTags: [
      { productId: "product-knit-ivory", label: "象牙针织", x: 46, y: 41 },
      { productId: "product-blazer-sand", label: "沙色外套", x: 63, y: 62 },
    ],
    title: "韩系宽松想穿得不臃肿，关键是上身的垂感",
    body: "我把针织做得更轻一点，再把颜色压到象牙白，整体就会很柔和，适合随手复制。",
    coverImage: demoImages.post3,
    styleTags: ["韩系宽松", "针织", "柔和配色"],
    likes: 148,
    createdAt: "2026-05-01T06:40:00.000Z",
    priceLabel: "¥139 起",
  },
  {
    id: "post-bomber-night",
    type: "seller-look",
    sellerId: "seller-urban",
    bloggerId: "blogger-nora",
    productId: "product-bomber-noir",
    productIds: ["product-bomber-noir", "product-jacket-black"],
    productTags: [
      { productId: "product-bomber-noir", label: "飞行夹克", x: 55, y: 38 },
      { productId: "product-jacket-black", label: "短夹克", x: 38, y: 60 },
    ],
    title: "黑色飞行夹克这样搭，周末出门很省心",
    body: "暗色飞行夹克配简单内搭，重点放在上短下长的比例，适合想要高街感但不想太夸张的日常。",
    coverImage: demoImages.tryOn1,
    styleTags: ["高街暗黑", "飞行夹克", "周末穿搭"],
    likes: 267,
    createdAt: "2026-05-01T05:50:00.000Z",
    priceLabel: "¥219 起",
  },
  {
    id: "post-olive-trench",
    type: "seller-look",
    sellerId: "seller-minimal",
    bloggerId: "blogger-mika",
    productId: "product-trench-olive",
    productIds: ["product-trench-olive", "product-blazer-sand"],
    productTags: [
      { productId: "product-trench-olive", label: "橄榄风衣", x: 50, y: 33 },
      { productId: "product-blazer-sand", label: "沙色西装", x: 62, y: 58 },
    ],
    title: "橄榄风衣比黑白灰更有记忆点",
    body: "把风衣换成低饱和橄榄色，通勤感还在，但视觉上更轻。内搭越简单，整体越稳。",
    coverImage: demoImages.product6,
    styleTags: ["通勤极简", "风衣", "橄榄色"],
    likes: 193,
    createdAt: "2026-05-01T05:05:00.000Z",
    priceLabel: "¥279 起",
  },
  {
    id: "post-denim-cafe",
    type: "seller-look",
    sellerId: "seller-vintage",
    bloggerId: "blogger-ryan",
    productId: "product-denim-wash",
    productIds: ["product-denim-wash"],
    productTags: [
      { productId: "product-denim-wash", label: "水洗牛仔", x: 48, y: 42 },
    ],
    title: "咖啡店拍照很出片的复古牛仔外套",
    body: "水洗牛仔不需要堆太多配饰，搭深色裤子和白色内搭就能有复古层次。",
    coverImage: demoImages.product2,
    styleTags: ["美式复古", "牛仔", "咖啡店穿搭"],
    likes: 142,
    createdAt: "2026-05-01T04:35:00.000Z",
    priceLabel: "¥168 起",
  },
  {
    id: "post-ivory-layer",
    type: "seller-look",
    sellerId: "seller-soft",
    bloggerId: "blogger-seo",
    productId: "product-knit-ivory",
    productIds: ["product-knit-ivory"],
    productTags: [
      { productId: "product-knit-ivory", label: "象牙针织", x: 52, y: 38 },
    ],
    title: "象牙白针织的松弛感，比纯白更温柔",
    body: "用同色系叠穿减少割裂感，宽松针织会让整体更像 OOTD 而不是基础款堆叠。",
    coverImage: demoImages.tryOn4,
    styleTags: ["韩系宽松", "针织", "同色系"],
    likes: 229,
    createdAt: "2026-05-01T03:30:00.000Z",
    priceLabel: "¥139 起",
  },
  {
    id: "post-sand-gallery",
    type: "seller-look",
    sellerId: "seller-minimal",
    bloggerId: "blogger-mika",
    productId: "product-blazer-sand",
    productIds: ["product-blazer-sand", "product-knit-ivory"],
    productTags: [
      { productId: "product-blazer-sand", label: "沙色西装", x: 54, y: 35 },
      { productId: "product-knit-ivory", label: "内搭针织", x: 42, y: 58 },
    ],
    title: "看展穿沙色西装，干净但不会太正式",
    body: "沙色宽松西装配浅色内搭，保留一点松弛感，适合不想穿得太商务的通勤和看展。",
    coverImage: demoImages.tryOn3,
    styleTags: ["Clean Fit", "西装", "看展穿搭"],
    likes: 318,
    createdAt: "2026-05-01T02:45:00.000Z",
    priceLabel: "¥249 起",
  },
  {
    id: "post-black-commute",
    type: "seller-look",
    sellerId: "seller-urban",
    bloggerId: "blogger-nora",
    productId: "product-jacket-black",
    productIds: ["product-jacket-black", "product-bomber-noir"],
    productTags: [
      { productId: "product-jacket-black", label: "黑色短夹克", x: 52, y: 36 },
      { productId: "product-bomber-noir", label: "暗黑外套", x: 63, y: 62 },
    ],
    title: "黑夹克通勤版：利落肩线真的很显精神",
    body: "这套把黑色夹克压得更日常，保留轮廓但不抢戏，适合办公室到晚间活动无缝切换。",
    coverImage: demoImages.product1,
    styleTags: ["高街暗黑", "通勤", "短夹克"],
    likes: 286,
    createdAt: "2026-05-01T01:55:00.000Z",
    priceLabel: "¥189 起",
  },
  ...seedRequests.map<Post>((request) => ({
    id: `post-${request.id}`,
    type: "buyer-request",
    requestId: request.id,
    title: `征集：${request.expectedItem}`,
    body: request.description,
    coverImage: request.image,
    styleTags: request.tags,
    likes: Math.floor(request.matchedOffers.length * 18 + 36),
    createdAt: request.createdAt,
    priceLabel: `预算 ¥${request.budget}`,
  })),
];

export const seedDemoState: DemoState = {
  sellers: seedSellers,
  bloggers: seedBloggers,
  products: seedProducts,
  posts: seedPosts,
  requests: seedRequests,
  collabRequests: [],
  viewer: {
    balance: 500,
    likedPostIds: [],
    savedPostIds: [],
    followedSellerIds: [],
    followedBloggerIds: [],
    favoriteProductIds: [],
    cartProductIds: [],
    sectionVisibility: {
      likedPosts: "public",
      savedPosts: "public",
      followedBloggers: "public",
      followedSellers: "public",
    },
    orders: [],
    viewHistory: [],
  },
};

export function buildDraftFromProduct(
  product: Product,
  seller: Seller,
): AIStyledPostDraft {
  const primaryTag = product.tags[0] ?? "风格穿搭";

  return {
    productId: product.id,
    sellerId: seller.id,
    title: `${primaryTag}今天这样穿，最容易出片`,
    caption: `把 ${product.name} 做成一套可直接复制的 ${primaryTag} 模板。上身重点是 ${product.tags
      .slice(1)
      .join(" / ")}，适合喜欢 ${seller.styleFocus} 的用户直接进商品看同款。`,
    modelImage: product.tryOnPreset,
    tags: product.tags,
    status: "ready",
  };
}

export function buildStyleAnalysis(input: string): StyleAnalysis {
  return {
    sourceType: "xhs-link",
    sourceInput: input,
    coverImage: demoImages.post4,
    styleTags: ["Clean Fit", "通勤极简", "大地色", "宽松西装"],
    summary:
      "整体是低饱和 clean fit 通勤风，核心在宽松西装、干净内搭和利落层次。适合买大地色外套或挺阔针织，再做一次试穿确认版型。",
    matchedProducts: [
      "product-blazer-sand",
      "product-trench-olive",
      "product-knit-ivory",
    ],
  };
}
