import type { Blogger } from "@/lib/types";

export type MockFollowerUser = {
  id: string;
  name: string;
  avatar: string;
  bio: string;
  styleTags: string[];
};

const surnames = ["周", "林", "陈", "王", "张", "李", "赵", "刘", "黄", "吴", "杨", "徐", "孙", "马", "朱", "胡", "郭", "何", "罗", "高", "宋", "郑", "梁", "谢", "韩", "唐", "冯", "于", "董", "萧", "程", "曹", "袁", "邓", "许", "傅", "沈", "曾", "彭", "吕", "苏", "卢", "蒋", "蔡", "贾", "丁", "魏", "薛", "叶", "阎"];
const chars = ["森", "然", "禾", "川", "白", "青", "墨", "简", "棉", "栗", "橘", "柚", "椰", "鹿", "鲸", "鹤", "猫", "熊", "兔", "鹿", "岚", "屿", "汀", "沐", "澄", "浅", "漾", "柠", "茶", "杏", "桃", "莓", "葵", "薇", "茉", "茶", "禾", "穗", "芒", "蒲", "苇", "芦", "竹", "枫", "榆", "槐", "桐", "樟", "槐", "椿"];
const stylePool = [
  "Clean Fit", "通勤极简", "高街暗黑", "美式复古", "韩系宽松",
  "日系工装", "甜酷", "松弛感", "牛仔", "夹克",
  "西装", "针织", "大地色", "黑白灰", "咖啡店穿搭",
  "看展穿搭", "周末出门", "显高穿搭", "预算友好", "AI试衣"
];
const avatarPool = ["周", "森", "CF", "M1", "林", "简", "K", "R", "陈", "白", "N", "Q", "张", "禾", "Y", "S", "李", "墨", "小", "C", "王", "棉", "D", "F", "赵", "栗", "T", "B", "刘", "橘", "P", "G", "黄", "椰", "H", "V", "吴", "鹿", "J", "W", "杨", "鲸", "X", "Z", "徐", "鹤", "U", "A", "孙", "猫", "L", "I", "马", "熊", "O", "E", "朱", "兔", "R1", "K2", "胡", "岚", "M2", "N1", "郭", "屿", "C1", "D1", "何", "汀", "S1", "T1", "罗", "沐", "B1", "F1", "高", "澄", "G1", "H1", "宋", "浅", "J1", "L1", "郑", "漾", "A1", "P1", "梁", "柠", "V1", "Z1", "谢", "茶", "E1", "Q1", "韩", "杏", "I1", "U1", "唐", "桃", "W1", "Y1", "冯", "莓", "X1", "O1", "于", "葵", "R2", "S2"];
const bios = [
  "每天都在找好看又显高的穿搭",
  "衣柜里永远少一件外套",
  "周末喜欢逛市集淘旧衣",
  "通勤穿搭困难户，求推荐",
  "喜欢把基础款穿出层次感",
  "热衷于黑白灰极简搭配",
  "预算有限但想穿出质感",
  "收藏了一百件夹克还没买",
  "跟着博主学穿搭中",
  "想用AI试衣找到适合自己的风格",
  "喜欢咖啡店拍照穿搭",
  "看展穿搭是我研究最久的",
  "追求松弛感的日常搭配",
  "韩系宽松是我的本命风格",
  "日系工装爱好者",
  "美式复古衣橱正在建设中",
  "高街暗黑风入门选手",
  "甜酷风穿搭小透明",
  "大地色系控",
  "针织衫收集爱好者",
  "西装外套永远不嫌多",
  "牛仔才是永远的神",
  "通勤极简风打工人",
  "周末出门穿搭每天不一样",
  "Clean Fit正在努力学习中",
  "显高穿搭笔记整理员",
  "喜欢用配饰丰富穿搭",
  "找同款找到眼花",
  "跟着季节换穿搭风格",
  "衣橱胶囊化践行者",
  "喜欢用一件亮色单品点睛",
  "叠穿是我最大的乐趣",
  "从基础款开始学穿搭",
  "喜欢收藏各种搭配灵感",
  "想买但还在观望清单很长",
  "每天刷穿搭帖子停不下来",
  "试衣间常客",
  "喜欢研究不同材质的搭配",
  "小个子穿搭研究者",
  "喜欢用同色系营造高级感",
  "衣柜大换季进行中",
  "喜欢淘小众设计师品牌",
  "想找到最适合自己的颜色",
  "穿搭日记坚持打卡中",
  "喜欢用一件复古单品提亮全身",
  "通勤休闲两不误的穿搭探索",
  "喜欢收集各种风格的搭配公式",
  "用穿搭表达自己的一天",
  "喜欢用不同剪裁玩转基础款",
  "衣橱里的衣服都要能互相搭配"
];

function at<T>(arr: T[], idx: number): T {
  return arr[((idx % arr.length) + arr.length) % arr.length];
}

function padId(num: number, len: number): string {
  return String(num).padStart(len, "0");
}

function generateFollowerUsers(count: number): MockFollowerUser[] {
  const users: MockFollowerUser[] = [];
  const prefixes = ["今天也要", "明天也要", "每天都在", "一直在", "努力", "喜欢", "沉迷", "专注", "研究", "探索", "记录", "分享", "寻找", "收藏", "种草", "拔草", "试穿", "搭配", "穿搭", "今天穿"];
  const suffixes = ["日记", "笔记", "灵感", "手册", "实验室", "研究所"];

  const nameTemplates = [
    (i: number) => `穿好看的${at(surnames, i)}`,
    (i: number) => `${at(chars, i)}在试衣`,
    (i: number) => `Clean Fit${at(surnames, i)}`,
    () => "城市通勤研究员",
    (i: number) => `${at(surnames, i)}的衣橱`,
    (i: number) => `${at(chars, i)}的穿搭笔记`,
    (i: number) => `${at(chars, i)}的周末穿搭`,
    (i: number) => `${at(surnames, i)}学穿搭`,
    (i: number) => `${at(chars, i)}搭配${at(suffixes, i)}`,
    (i: number) => `极简${at(surnames, i)}`,
    (i: number) => `${at(surnames, i)}的日常穿搭`,
    (i: number) => `${at(chars, i)}的OOTD`,
    (i: number) => `${at(surnames, i)}的显高穿搭`,
    (i: number) => `小个子${at(surnames, i)}`,
    (i: number) => `通勤${at(surnames, i)}`,
    (i: number) => `${at(chars, i)}的黑白灰`,
    (i: number) => `${at(surnames, i)}的甜酷风`,
    (i: number) => `复古${at(surnames, i)}`,
    (i: number) => `${at(chars, i)}的松弛感`,
    (i: number) => `${at(surnames, i)}的工装日记`,
  ];

  for (let i = 1; i <= count; i++) {
    const id = `user-follower-${padId(i, 4)}`;
    const idx = i - 1;
    const prefix = at(prefixes, idx);
    const nameTemplate = nameTemplates[idx % nameTemplates.length];
    const namePart = nameTemplate(idx);
    const name = idx % 3 === 0 ? `${prefix}${namePart}` : namePart;
    const avatar = at(avatarPool, idx);
    const bio = at(bios, idx);
    const tagCount = 2 + (idx % 4);
    const styleTags: string[] = [];
    for (let t = 0; t < tagCount; t++) {
      styleTags.push(at(stylePool, idx * 3 + t));
    }
    users.push({ id, name, avatar, bio, styleTags });
  }
  return users;
}

export const mockFollowerUsers: MockFollowerUser[] = generateFollowerUsers(1200);

export const mockBloggerAccounts: Blogger[] = [
  {
    id: "blogger-mock-001",
    name: "阿森黑白日常",
    avatar: "阿黑",
    bio: "黑白灰极简穿搭，通勤也能穿出质感与高级感",
    followerCount: 680,
    styleTags: ["黑白灰", "通勤极简", "Clean Fit", "松弛感"],
    coverImage: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "blogger-mock-002",
    name: "Niko通勤实验室",
    avatar: "NK",
    bio: "打工人一周穿搭不重样，用基础款搭出通勤高级感",
    followerCount: 920,
    styleTags: ["通勤极简", "西装", "Clean Fit", "黑白灰"],
    coverImage: "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "blogger-mock-003",
    name: "小乔Clean Fit",
    avatar: "乔C",
    bio: "专注Clean Fit风格解析，教你用最少的单品穿出最好的质感",
    followerCount: 450,
    styleTags: ["Clean Fit", "松弛感", "大地色", "预算友好"],
    coverImage: "https://images.unsplash.com/photo-1487222477894-8943e31ef7b2?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "blogger-mock-004",
    name: "Ryan复古衣橱",
    avatar: "R复古",
    bio: "美式复古与日系工装的碰撞，旧衣新穿的无限可能",
    followerCount: 780,
    styleTags: ["美式复古", "日系工装", "夹克", "牛仔"],
    coverImage: "https://images.unsplash.com/photo-1552374196-1ab2a1c593e8?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "blogger-mock-005",
    name: "栗子的甜酷手册",
    avatar: "栗甜",
    bio: "甜酷风日常搭配分享，甜而不腻酷而不冷",
    followerCount: 530,
    styleTags: ["甜酷", "韩系宽松", "针织", "周末出门"],
    coverImage: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "blogger-mock-006",
    name: "墨川高街日记",
    avatar: "墨川",
    bio: "高街暗黑风日常穿搭探索，用黑色穿出层次与态度",
    followerCount: 860,
    styleTags: ["高街暗黑", "黑白灰", "夹克", "显高穿搭"],
    coverImage: "https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "blogger-mock-007",
    name: "林小白的咖啡店穿搭",
    avatar: "林咖",
    bio: "周末咖啡店拍照穿搭灵感，松弛感与氛围感并存",
    followerCount: 350,
    styleTags: ["咖啡店穿搭", "松弛感", "针织", "大地色"],
    coverImage: "https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "blogger-mock-008",
    name: "韩系宽松研究所",
    avatar: "韩研",
    bio: "韩系宽松穿搭全攻略，舒适与好看可以兼得",
    followerCount: 710,
    styleTags: ["韩系宽松", "松弛感", "针织", "预算友好"],
    coverImage: "https://images.unsplash.com/photo-1504198458649-3128b932625d?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "blogger-mock-009",
    name: "周周的显高穿搭笔记",
    avatar: "周显",
    bio: "155cm小个子显高穿搭实录，比例才是关键",
    followerCount: 990,
    styleTags: ["显高穿搭", "通勤极简", "Clean Fit", "西装"],
    coverImage: "https://images.unsplash.com/photo-1495385794356-15371f348c31?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "blogger-mock-010",
    name: "BudgetQueen预算友好穿搭",
    avatar: "BQ",
    bio: "平价也能穿出高级感，预算友好穿搭分享达人",
    followerCount: 420,
    styleTags: ["预算友好", "Clean Fit", "黑白灰", "通勤极简"],
    coverImage: "https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "blogger-mock-011",
    name: "看展穿搭收藏家",
    avatar: "展搭",
    bio: "美术馆和画廊穿搭灵感，看展也要穿出艺术感",
    followerCount: 640,
    styleTags: ["看展穿搭", "黑白灰", "松弛感", "大地色"],
    coverImage: "https://images.unsplash.com/photo-1550614000-4b9519e02a48?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "blogger-mock-012",
    name: "陈大地的工装日常",
    avatar: "陈工",
    bio: "日系工装与美式复古的混搭日常，功能与美学兼顾",
    followerCount: 890,
    styleTags: ["日系工装", "美式复古", "夹克", "牛仔"],
    coverImage: "https://images.unsplash.com/photo-1542272604-787c3835535d?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "blogger-mock-013",
    name: "周末出门穿搭局",
    avatar: "周出",
    bio: "周末出门不知道穿什么？每天一套look给你灵感",
    followerCount: 560,
    styleTags: ["周末出门", "韩系宽松", "甜酷", "预算友好"],
    coverImage: "https://images.unsplash.com/photo-1485968579580-b6d095142e6e?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "blogger-mock-014",
    name: "AI试衣体验官小唐",
    avatar: "AI唐",
    bio: "用AI试衣探索不同风格，技术让穿搭更简单",
    followerCount: 870,
    styleTags: ["AI试衣", "Clean Fit", "通勤极简", "甜酷"],
    coverImage: "https://images.unsplash.com/photo-1469334031218-e382a71b716b?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "blogger-mock-015",
    name: "王森的牛仔档案",
    avatar: "森牛",
    bio: "牛仔穿搭全品类解析，一条牛仔裤的N种穿法",
    followerCount: 750,
    styleTags: ["牛仔", "美式复古", "松弛感", "高街暗黑"],
    coverImage: "https://images.unsplash.com/photo-1582552938357-32b906df40cb?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "blogger-mock-016",
    name: "针织控的衣橱",
    avatar: "针织",
    bio: "一年四季穿针织，柔软材质穿出不同风格的可能性",
    followerCount: 610,
    styleTags: ["针织", "大地色", "通勤极简", "咖啡店穿搭"],
    coverImage: "https://images.unsplash.com/photo-1434389677669-e08b4cda3a0a?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "blogger-mock-017",
    name: "西装控小刘",
    avatar: "刘西",
    bio: "西装穿搭不只有通勤，用一件西装玩转多种场景",
    followerCount: 520,
    styleTags: ["西装", "通勤极简", "高街暗黑", "黑白灰"],
    coverImage: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "blogger-mock-018",
    name: "大地色系爱好者小吴",
    avatar: "吴大",
    bio: "大地色穿搭研究，温暖质感贯穿四季的配色哲学",
    followerCount: 480,
    styleTags: ["大地色", "Clean Fit", "日系工装", "松弛感"],
    coverImage: "https://images.unsplash.com/photo-1475180429745-4c63b8e6c09a?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "blogger-mock-019",
    name: "夹克收藏家杨杨",
    avatar: "杨夹",
    bio: "从牛仔夹克到机车皮衣，夹克穿搭全覆盖",
    followerCount: 930,
    styleTags: ["夹克", "高街暗黑", "美式复古", "日系工装"],
    coverImage: "https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "blogger-mock-020",
    name: "松弛感穿搭指南",
    avatar: "松弛",
    bio: "不费力的好看，松弛感穿搭的日常实践",
    followerCount: 840,
    styleTags: ["松弛感", "韩系宽松", "大地色", "预算友好"],
    coverImage: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "blogger-mock-021",
    name: "极简风穿搭师Luna",
    avatar: "Lu",
    bio: "少即是多，用极简穿搭打造个人风格标识",
    followerCount: 2300,
    styleTags: ["通勤极简", "Clean Fit", "黑白灰", "松弛感"],
    coverImage: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "blogger-mock-022",
    name: "街头潮人阿K",
    avatar: "K街",
    bio: "高街暗黑与街头文化的融合，用穿搭表达态度",
    followerCount: 4500,
    styleTags: ["高街暗黑", "美式复古", "夹克", "显高穿搭"],
    coverImage: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "blogger-mock-023",
    name: "韩系穿搭师Mina",
    avatar: "Mi",
    bio: "韩系宽松穿搭与甜酷风格切换，温柔中带着酷感",
    followerCount: 6200,
    styleTags: ["韩系宽松", "甜酷", "针织", "周末出门"],
    coverImage: "https://images.unsplash.com/photo-1491349174775-aaafddd81942?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "blogger-mock-024",
    name: "复古猎人Jason",
    avatar: "Ja",
    bio: "穿梭于古着店和市集，发现复古穿搭的无限魅力",
    followerCount: 3800,
    styleTags: ["美式复古", "日系工装", "牛仔", "大地色"],
    coverImage: "https://images.unsplash.com/photo-1552374196-1ab2a1c593e8?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "blogger-mock-025",
    name: "日系工装师山本",
    avatar: "山工",
    bio: "日系工装风格深度解析，城市户外的混搭美学",
    followerCount: 5100,
    styleTags: ["日系工装", "松弛感", "大地色", "夹克"],
    coverImage: "https://images.unsplash.com/photo-1516826957135-700dedea698c?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "blogger-mock-026",
    name: "甜酷女孩Vivi",
    avatar: "Vi",
    bio: "甜酷风进阶教学，甜度和酷感的完美平衡点",
    followerCount: 8900,
    styleTags: ["甜酷", "韩系宽松", "西装", "黑白灰"],
    coverImage: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "blogger-mock-027",
    name: "通勤穿搭师Carol",
    avatar: "Ca",
    bio: "工作日穿搭不无聊，通勤也能穿出自己的风格",
    followerCount: 7200,
    styleTags: ["通勤极简", "Clean Fit", "西装", "针织"],
    coverImage: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "blogger-mock-028",
    name: "周末穿搭师Max",
    avatar: "Ma",
    bio: "从周五晚上到周日晚上，周末穿搭全场景覆盖",
    followerCount: 1500,
    styleTags: ["周末出门", "韩系宽松", "预算友好", "松弛感"],
    coverImage: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "blogger-mock-029",
    name: "显高穿搭师小雅",
    avatar: "雅显",
    bio: "158cm穿出165cm的视觉效果，比例调整的秘密",
    followerCount: 3400,
    styleTags: ["显高穿搭", "Clean Fit", "通勤极简", "黑白灰"],
    coverImage: "https://images.unsplash.com/photo-1502823403490-4227d047545a?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "blogger-mock-030",
    name: "平价穿搭师小鱼",
    avatar: "鱼平",
    bio: "用有限的预算搭出无限的风格，平价不低质",
    followerCount: 9100,
    styleTags: ["预算友好", "韩系宽松", "甜酷", "通勤极简"],
    coverImage: "https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "blogger-mock-031",
    name: "黑白灰穿搭师Zack",
    avatar: "Zack",
    bio: "用黑白灰三色打造高级感衣橱，极简不等于单调",
    followerCount: 2800,
    styleTags: ["黑白灰", "通勤极简", "高街暗黑", "Clean Fit"],
    coverImage: "https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "blogger-mock-032",
    name: "咖啡店穿搭师Lily",
    avatar: "Lily",
    bio: "咖啡店打卡穿搭灵感库，慵懒与精致并存",
    followerCount: 4200,
    styleTags: ["咖啡店穿搭", "针织", "大地色", "松弛感"],
    coverImage: "https://images.unsplash.com/photo-1487222477894-8943e31ef7b2?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "blogger-mock-033",
    name: "看展穿搭 curator Chen",
    avatar: "Cur陈",
    bio: "美术馆穿搭灵感策展人，用穿搭呼应艺术氛围",
    followerCount: 5600,
    styleTags: ["看展穿搭", "黑白灰", "Clean Fit", "松弛感"],
    coverImage: "https://images.unsplash.com/photo-1550614000-4b9519e02a48?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "blogger-mock-034",
    name: "Clean Fit导师Mark",
    avatar: "Mk",
    bio: "Clean Fit风格系统教学，干净利落的穿搭哲学",
    followerCount: 12000,
    styleTags: ["Clean Fit", "通勤极简", "黑白灰", "大地色"],
    coverImage: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "blogger-mock-035",
    name: "高街暗黑师Raven",
    avatar: "Rv",
    bio: "暗色系穿搭进阶指南，暗黑不等于沉闷",
    followerCount: 18500,
    styleTags: ["高街暗黑", "夹克", "黑白灰", "牛仔"],
    coverImage: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "blogger-mock-036",
    name: "美式复古师Derek",
    avatar: "Dr",
    bio: "从70s到90s，美式复古穿搭的时代风格演变",
    followerCount: 8200,
    styleTags: ["美式复古", "牛仔", "夹克", "日系工装"],
    coverImage: "https://images.unsplash.com/photo-1542272604-787c3835535d?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "blogger-mock-037",
    name: "甜酷风格师Jade",
    avatar: "Jd",
    bio: "甜酷风格混搭实验，甜美与酷感的化学反应",
    followerCount: 14300,
    styleTags: ["甜酷", "西装", "韩系宽松", "周末出门"],
    coverImage: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "blogger-mock-038",
    name: "日系穿搭师Haru",
    avatar: "Ha",
    bio: "日系穿搭的氛围感营造，细节决定一切",
    followerCount: 9800,
    styleTags: ["日系工装", "大地色", "松弛感", "针织"],
    coverImage: "https://images.unsplash.com/photo-1516826957135-700dedea698c?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "blogger-mock-039",
    name: "松弛感穿搭师Soo",
    avatar: "Soo",
    bio: "不费力的穿搭美学，松弛感背后的精心搭配",
    followerCount: 6700,
    styleTags: ["松弛感", "韩系宽松", "针织", "大地色"],
    coverImage: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "blogger-mock-040",
    name: "牛仔穿搭师Denim Dan",
    avatar: "Dn",
    bio: "牛仔穿搭百科全书，从原牛到水洗的全风格覆盖",
    followerCount: 4800,
    styleTags: ["牛仔", "美式复古", "高街暗黑", "日系工装"],
    coverImage: "https://images.unsplash.com/photo-1582552938357-32b906df40cb?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "blogger-mock-041",
    name: "西装穿搭师Ethan",
    avatar: "Et",
    bio: "西装穿搭场景化教学，从职场到party的西装切换",
    followerCount: 21000,
    styleTags: ["西装", "通勤极简", "Clean Fit", "高街暗黑"],
    coverImage: "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "blogger-mock-042",
    name: "针织穿搭师Woolly",
    avatar: "Wo",
    bio: "针织材质穿搭指南，柔软与层次感的完美结合",
    followerCount: 11200,
    styleTags: ["针织", "大地色", "咖啡店穿搭", "松弛感"],
    coverImage: "https://images.unsplash.com/photo-1434389677669-e08b4cda3a0a?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "blogger-mock-043",
    name: "大地色系师Earthy",
    avatar: "Er",
    bio: "大地色穿搭色彩学，温暖色调的高级搭配法则",
    followerCount: 7500,
    styleTags: ["大地色", "日系工装", "Clean Fit", "通勤极简"],
    coverImage: "https://images.unsplash.com/photo-1475180429745-4c63b8e6c09a?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "blogger-mock-044",
    name: "黑白灰大师Mono",
    avatar: "Mo",
    bio: "黑白灰穿搭的色彩魔法，单色不单调的穿搭秘诀",
    followerCount: 15600,
    styleTags: ["黑白灰", "高街暗黑", "通勤极简", "Clean Fit"],
    coverImage: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "blogger-mock-045",
    name: "AI试衣体验师Ava",
    avatar: "Av",
    bio: "AI穿搭体验先锋科技与时尚的跨界穿搭探索",
    followerCount: 13800,
    styleTags: ["AI试衣", "Clean Fit", "甜酷", "周末出门"],
    coverImage: "https://images.unsplash.com/photo-1469334031218-e382a71b716b?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "blogger-mock-046",
    name: "预算穿搭师Penny",
    avatar: "Pe",
    bio: "低预算高颜值的穿搭方案，省钱也有好品味",
    followerCount: 25000,
    styleTags: ["预算友好", "通勤极简", "韩系宽松", "Clean Fit"],
    coverImage: "https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "blogger-mock-047",
    name: "通勤极简师Ivy",
    avatar: "Iv",
    bio: "通勤穿搭效率化，用最少的时间搭出最好的look",
    followerCount: 19200,
    styleTags: ["通勤极简", "Clean Fit", "西装", "黑白灰"],
    coverImage: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "blogger-mock-048",
    name: "周末穿搭局主理人Owen",
    avatar: "Ow",
    bio: "周末穿搭灵感制造机，休闲场景的风格切换",
    followerCount: 8700,
    styleTags: ["周末出门", "松弛感", "韩系宽松", "预算友好"],
    coverImage: "https://images.unsplash.com/photo-1485968579580-b6d095142e6e?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "blogger-mock-049",
    name: "显高穿搭导师TallTales",
    avatar: "TT",
    bio: "小个子穿搭进阶课堂，155也能穿出大长腿视觉效果",
    followerCount: 16800,
    styleTags: ["显高穿搭", "Clean Fit", "高街暗黑", "甜酷"],
    coverImage: "https://images.unsplash.com/photo-1502823403490-4227d047545a?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "blogger-mock-050",
    name: "咖啡店穿搭师Brew",
    avatar: "Br",
    bio: "咖啡店场景穿搭灵感合集，慵懒下午茶的最佳搭配",
    followerCount: 5400,
    styleTags: ["咖啡店穿搭", "针织", "大地色", "松弛感"],
    coverImage: "https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "blogger-mock-051",
    name: "看展穿搭灵感师Muse",
    avatar: "Mu",
    bio: "美术馆穿搭进阶指南，用穿搭呼应不同展览的风格",
    followerCount: 32000,
    styleTags: ["看展穿搭", "黑白灰", "Clean Fit", "通勤极简"],
    coverImage: "https://images.unsplash.com/photo-1550614000-4b9519e02a48?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "blogger-mock-052",
    name: "夹克搭配师Blazer",
    avatar: "Bl",
    bio: "夹克穿搭大全，从春秋到冬日夹克的N种搭配方式",
    followerCount: 44000,
    styleTags: ["夹克", "高街暗黑", "美式复古", "日系工装"],
    coverImage: "https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "blogger-mock-053",
    name: "甜酷实验室主理人Nova",
    avatar: "No",
    bio: "甜酷风格实验场，探索甜美与酷感的新组合",
    followerCount: 52000,
    styleTags: ["甜酷", "韩系宽松", "西装", "周末出门"],
    coverImage: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "blogger-mock-054",
    name: "Clean Fit美学师Clean",
    avatar: "Cl",
    bio: "Clean Fit美学体系构建，干净穿搭的深度解析",
    followerCount: 61000,
    styleTags: ["Clean Fit", "通勤极简", "黑白灰", "松弛感"],
    coverImage: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "blogger-mock-055",
    name: "高街文化师Street",
    avatar: "St",
    bio: "高街文化穿搭先锋，街头与高级时装的融合艺术",
    followerCount: 72000,
    styleTags: ["高街暗黑", "夹克", "牛仔", "黑白灰"],
    coverImage: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "blogger-mock-056",
    name: "日系美学师Zen",
    avatar: "Ze",
    bio: "日系穿搭美学深度探索，侘寂与穿搭的哲学连接",
    followerCount: 38000,
    styleTags: ["日系工装", "大地色", "松弛感", "针织"],
    coverImage: "https://images.unsplash.com/photo-1516826957135-700dedea698c?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "blogger-mock-057",
    name: "美式复古档案师Archive",
    avatar: "Ar",
    bio: "美式复古穿搭档案馆，经典单品的新旧演绎",
    followerCount: 47000,
    styleTags: ["美式复古", "牛仔", "大地色", "夹克"],
    coverImage: "https://images.unsplash.com/photo-1542272604-787c3835535d?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "blogger-mock-058",
    name: "通勤穿搭女王Boss",
    avatar: "Bo",
    bio: "职场穿搭进阶指南，用穿搭提升职场自信与气场",
    followerCount: 55000,
    styleTags: ["通勤极简", "西装", "Clean Fit", "黑白灰"],
    coverImage: "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "blogger-mock-059",
    name: "穿搭预算魔法师Save",
    avatar: "Sa",
    bio: "用极低的预算穿出极高的质感，预算管理的穿搭智慧",
    followerCount: 68000,
    styleTags: ["预算友好", "韩系宽松", "甜酷", "通勤极简"],
    coverImage: "https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "blogger-mock-060",
    name: "全风格穿搭师Omni",
    avatar: "Om",
    bio: "从极简到高街无所不穿，全风格穿搭探索者",
    followerCount: 78000,
    styleTags: ["Clean Fit", "高街暗黑", "甜酷", "周末出门"],
    coverImage: "https://images.unsplash.com/photo-1469334031218-e382a71b716b?auto=format&fit=crop&w=1200&q=80",
  },
];
